default_language_version:
  python: python3.8
repos:
  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: poetry run isort
      pass_filenames: true
      language: system
      types: [python]
  - repo: local
    hooks:
    - id: black
      name: black
      entry: poetry run black
      pass_filenames: true
      language: system
      types: [python]
  - repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types: [python]
  - repo: local
    hooks:
    - id: poetry
      name: poetry check
      entry: poetry check
      pass_filenames: false
      language: system
      files: ^pyproject\.toml$
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: poetry run mypy -p hassio_wb_discovery --sqlite-cache
      pass_filenames: false
      language: system
      types: [python]
