mqtt:
  host: 192.168.1.2
  port: 1883
devices:
  # My relays control mostly lights, so I use "light" type by default
  x-relay: &default-relay
    exclude_controls:
      - "^Input \\d+ (counter|freq)$"  # These values have no practical value to me
    controls: &default-relay-controls
      K1:
        force_type: light
      K2:
        force_type: light
      K3:
        force_type: light
      K4:
        force_type: light
      K5:
        force_type: light
      K6:
        force_type: light

  wb-mr3_27: *default-relay
  wb-mr3_32: *default-relay
  wb-mr6c_11:
    <<: *default-relay
    controls:
      <<: *default-relay-controls
      K6:
        force_type: fan
  wb-mr6c_19:
    <<: *default-relay
    controls:
      <<: *default-relay-controls
      K5:
        force_type: fan
  wb-map6s_20:
    exclude_controls:
      - "^.* [1-6]$"  # I don't have any MAP6S inputs connected right now
    controls:
      Frequency:
        overrides:
          unit_of_measurement: Hz
